version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      eslint:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint*'
      gatsby:
        patterns:
          - 'gatsby*'
      react:
        patterns:
          - 'react*'
          - '@types/react*'
      stylelint:
        patterns:
          - 'stylelint*'
